library(tidyverse)
library(readr)
options(max.print = 50)
temp <- tempfile(fileext = ".zip")
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
cols_consumption <- colnames(read.table(unz(temp, "household_power_consumption.txt"),header=TRUE,sep=";",nrow=2))
consumption <- read.table(unz(temp, "household_power_consumption.txt"),header=TRUE,col.names=cols_consumption,sep=";", skip=66636, nrows=2880)
consumption$Date <- parse_date(consumption$Date, "%d/%m/%Y")
consumption$Time <- parse_time(consumption$Time, "%H:%M:%S")
head(consumption)
consumption$Datetime <- as.POSIXct(paste(consumption$Date,consumption$Time))

plot(consumption$Datetime,consumption$Global_active_power, type ="l", ylab="Global Active Power (kilowatts)", xlab = "")
